#!/usr/bin/env Rscript
# analyze_csv.R - Performs descriptive analysis on a CSV file - TO REFINE
# Usage: Rscript analyze_csv.R <input_file> <output_file>

# Check command line arguments
args <- commandArgs(trailingOnly = TRUE)
if (length(args) < 2) {
  stop("Usage: Rscript analyze_csv.R <input_file> <output_file>")
}

input_file <- args[1]
output_file <- args[2]

# Load required libraries
suppressPackageStartupMessages({
  library(tidyverse)
  library(knitr)
  library(rmarkdown)
  library(DT)
})

# Read the CSV file
cat("Reading file:", input_file, "\n")
data <- tryCatch({
  read.csv(input_file, stringsAsFactors = FALSE)
}, error = function(e) {
  stop("Error reading CSV file: ", e$message)
})

# Perform basic descriptive analysis
cat("Analyzing data...\n")
summary_stats <- summary(data)
numeric_cols <- sapply(data, is.numeric)
correlation_matrix <- NULL
if (sum(numeric_cols) > 1) {
  correlation_matrix <- cor(data[, numeric_cols], use = "pairwise.complete.obs")
}

# Generate HTML report
cat("Generating report...\n")
rmarkdown::render(
  input = textConnection('
---
title: "Biomarker Descriptive Analysis"
date: "`r format(Sys.time(), "%Y-%m-%d %H:%M:%S")`"
output: 
  html_document:
    theme: cosmo
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

## Dataset Overview

**File analyzed:** `r basename(input_file)`

**Number of observations:** `r nrow(data)`

**Number of variables:** `r ncol(data)`

## Data Structure

```{r}
DT::datatable(head(data, 20), 
              options = list(scrollX = TRUE, pageLength = 5),
              caption = "First 20 rows of data")
```

## Summary Statistics

```{r}
knitr::kable(as.data.frame(summary_stats))
```

## Column Types

```{r}
col_types <- data.frame(
  Column = names(data),
  Type = sapply(data, class),
  Missing = sapply(data, function(x) sum(is.na(x))),
  `Missing %` = round(sapply(data, function(x) sum(is.na(x)) / length(x) * 100), 2)
)
DT::datatable(col_types)
```

## Distribution of Numeric Variables

```{r fig.height=8, fig.width=10}
if (sum(numeric_cols) > 0) {
  numeric_data <- data[, numeric_cols, drop = FALSE]
  par(mfrow = c(min(3, sum(numeric_cols)), min(3, ceiling(sum(numeric_cols)/3))))
  for (col in names(numeric_data)) {
    hist(numeric_data[[col]], main = col, xlab = col, col = "skyblue")
  }
}
```

## Correlation Matrix

```{r}
if (!is.null(correlation_matrix)) {
  DT::datatable(round(correlation_matrix, 2),
                options = list(scrollX = TRUE, pageLength = 10))
}
```

## Additional Notes

This is an automated report generated by the biomarker analysis system.

  '),
  output_file = output_file,
  output_format = "html_document"
)

cat("Analysis complete. Report saved to:", output_file, "\n")